const extra = {
'zh-Hant':{privateExercise:'私人 · 五項練習',screeningTitle:'簡短認知練習',disclaimer:'這不是診斷，也不能確認或排除任何疾病。',howTitle:'如何完成練習',how1:'每頁只需完成畫面上的一項任務。',how2:'完成後按「確認」提交；答案不必正確也可以繼續。',how3:'時鐘題可直接點擊鐘面，先設定小時，再設定分鐘。',how4:'請盡量自行完成，途中可隨時休息。',start:'開始',clockTitle:'請把時鐘設定為 10:50',clockHelp:'點擊鐘面設定小時，然後再點擊設定分鐘。',setHour:'設定小時',setMinute:'設定分鐘',reset:'重設',confirm:'確認',recallTitle:'記住三個詞語',word1:'蘋果',word2:'椅子',word3:'河流',recallHelp:'讀完並嘗試記住後，勾選完成。',doneReading:'我已讀完並嘗試記住',attentionTitle:'倒轉輸入數字 7 2 9',attentionHelp:'請在方格輸入倒轉後的數字。',languageTitle:'寫出一種動物',languageHelp:'任何動物名稱都可以。',delayedTitle:'輸入剛才記住的三個詞語',delayedHelp:'不確定也沒關係，輸入你記得的內容即可。',confirmFinish:'確認並完成',completeTitle:'練習已完成',completeText:'謝謝你完成所有任務。表現好壞不等同診斷。',completeNote:'如你對記憶或日常生活有持續擔心，請向合資格醫護人員查詢。',required:'請先完成這項任務，再按確認。',hourMode:'請點擊鐘面設定小時',minuteMode:'請點擊鐘面設定分鐘',saved:'已完成。'},
'zh-Hans':{privateExercise:'私人 · 五项练习',screeningTitle:'简短认知练习',disclaimer:'这不是诊断，也不能确认或排除任何疾病。',howTitle:'如何完成练习',how1:'每页只需完成画面上的一项任务。',how2:'完成后按“确认”提交；答案不必正确也可以继续。',how3:'时钟题可直接点击钟面，先设置小时，再设置分钟。',how4:'请尽量自行完成，途中可随时休息。',start:'开始',clockTitle:'请把时钟设置为 10:50',clockHelp:'点击钟面设置小时，然后再点击设置分钟。',setHour:'设置小时',setMinute:'设置分钟',reset:'重设',confirm:'确认',recallTitle:'记住三个词语',word1:'苹果',word2:'椅子',word3:'河流',recallHelp:'读完并尝试记住后，勾选完成。',doneReading:'我已读完并尝试记住',attentionTitle:'倒转输入数字 7 2 9',attentionHelp:'请在方格输入倒转后的数字。',languageTitle:'写出一种动物',languageHelp:'任何动物名称都可以。',delayedTitle:'输入刚才记住的三个词语',delayedHelp:'不确定也没关系，输入你记得的内容即可。',confirmFinish:'确认并完成',completeTitle:'练习已完成',completeText:'谢谢你完成所有任务。表现好坏不等同诊断。',completeNote:'如你对记忆或日常生活有持续担心，请向合资格医护人员查询。',required:'请先完成这项任务，再按确认。',hourMode:'请点击钟面设置小时',minuteMode:'请点击钟面设置分钟',saved:'已完成。'},
en:{privateExercise:'Private · five exercises',screeningTitle:'Short cognitive exercise',disclaimer:'This is not a diagnosis and cannot confirm or rule out any condition.',howTitle:'How to complete the exercise',how1:'Complete the single task shown on each page.',how2:'Select Confirm when done. Your answer does not need to be correct to continue.',how3:'For the clock, click the face to set the hour, then the minutes.',how4:'Try each task yourself and take a break whenever needed.',start:'Start',clockTitle:'Set the clock to 10:50',clockHelp:'Click the face to set the hour, then click again to set the minutes.',setHour:'Set hour',setMinute:'Set minutes',reset:'Reset',confirm:'Confirm',recallTitle:'Remember three words',word1:'Apple',word2:'Chair',word3:'River',recallHelp:'After reading and trying to remember them, mark the task complete.',doneReading:'I have read and tried to remember them',attentionTitle:'Enter 7 2 9 in reverse order',attentionHelp:'Type the reversed digits in the box.',languageTitle:'Write the name of an animal',languageHelp:'Any animal name is acceptable.',delayedTitle:'Enter the three words from earlier',delayedHelp:'It is okay to be unsure. Enter whatever you remember.',confirmFinish:'Confirm and finish',completeTitle:'Exercise complete',completeText:'Thank you for completing every task. Performance is not a diagnosis.',completeNote:'If concerns about memory or daily life persist, speak with a qualified healthcare professional.',required:'Complete this task before selecting Confirm.',hourMode:'Click the clock face to set the hour',minuteMode:'Click the clock face to set the minutes',saved:'Completed.'}}
const baseT=window.t; window.t=k=>extra[window.currentLang()]?.[k]||baseT(k); window.applyTranslations();
const pages=[...document.querySelectorAll('[data-page]')],steps=[...document.querySelectorAll('.step')]; let pageIndex=0;
const scores={}; let hour=12,minute=0,mode='hour',clockTouched=false;
const clock=document.querySelector('#clock-face'),hit=document.querySelector('#clock-hit'),hourHand=document.querySelector('#hour-hand'),minuteHand=document.querySelector('#minute-hand');
for(let i=0;i<60;i++){const a=i*6*Math.PI/180,major=i%5===0,line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',50+Math.sin(a)*(major?40:42));line.setAttribute('y1',50-Math.cos(a)*(major?40:42));line.setAttribute('x2',50+Math.sin(a)*45);line.setAttribute('y2',50-Math.cos(a)*45);line.setAttribute('class',`clock-tick${major?' major':''}`);document.querySelector('#clock-ticks').append(line)}
for(let n=1;n<=12;n++){const a=n*30*Math.PI/180,t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',50+Math.sin(a)*35);t.setAttribute('y',50-Math.cos(a)*35);t.textContent=n;document.querySelector('#clock-numbers').append(t)}
function setMode(m){mode=m;document.querySelector('#set-hour').classList.toggle('active',m==='hour');document.querySelector('#set-minute').classList.toggle('active',m==='minute');document.querySelector('#clock-instruction').textContent=window.t(m==='hour'?'hourMode':'minuteMode')}
function updateClock(){hourHand.style.transform=`rotate(${((hour%12)+minute/60)*30}deg)`;minuteHand.style.transform=`rotate(${minute*6}deg)`;document.querySelector('#clock-readout').textContent=`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`}
hit.addEventListener('pointerdown',e=>{const r=clock.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100-50,y=(e.clientY-r.top)/r.height*100-50,a=(Math.atan2(x,-y)*180/Math.PI+360)%360;clockTouched=true;if(mode==='hour'){const h=Math.round(a/30)%12;hour=h||12;setMode('minute')}else minute=Math.round(a/6)%60;updateClock()});
document.querySelector('#set-hour').onclick=()=>setMode('hour');document.querySelector('#set-minute').onclick=()=>setMode('minute');document.querySelector('#reset-clock').onclick=()=>{hour=12;minute=0;clockTouched=false;setMode('hour');updateClock()};
function show(i){pageIndex=i;pages.forEach((p,j)=>p.hidden=j!==i);steps.forEach((s,j)=>{s.classList.toggle('active',j===i);s.classList.toggle('complete',j<i)});pages[i].querySelector('input,textarea,button')?.focus()}
function complete(page){const name=page.dataset.page,validation=page.querySelector('.validation');let done=true,score=1;if(name==='clock'){done=clockTouched;score=hour===10&&minute===50?1:0}else if(name==='recall'){done=page.querySelector('[data-complete]').checked}else if(name==='attention'){const v=page.querySelector('input').value.trim();done=Boolean(v);score=v==='927'?1:0}else if(name==='language'){done=Boolean(page.querySelector('input').value.trim())}else if(name==='delayed'){const v=page.querySelector('textarea').value.trim().toLowerCase();done=Boolean(v);const words=window.currentLang()==='en'?['apple','chair','river']:window.currentLang()==='zh-Hans'?['苹果','椅子','河流']:['蘋果','椅子','河流'];score=words.every(w=>v.includes(w))?1:0}if(!done){validation.textContent=window.t('required');return}validation.textContent='';scores[name]=score;if(pageIndex<pages.length-1)show(pageIndex+1);else finish()}
pages[0].querySelector('[data-next]').onclick=()=>show(1);document.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=()=>complete(b.closest('[data-page]')));
function finish(){pages[pageIndex].hidden=true;steps.forEach(s=>{s.classList.remove('active');s.classList.add('complete')});document.querySelector('#screening-result').hidden=false}
window.addEventListener('languagechange',()=>{window.applyTranslations();setMode(mode)});setMode('hour');updateClock();
